import React, { createContext, useContext, useState } from 'react';

const LangContext = createContext();

export const translations = {
  it: {
    appSubtitle: 'Industrial Design AI',
    heroTitle: 'Da idea a sketch',
    heroTitleAccent: 'professionale',
    heroDesc: 'Carica una foto, un disegno o una bozza e trasformalo in uno sketch di industrial design con colori Pantone.',
    restart: 'Ricomincia',
    settings: 'Impostazioni',
    settingsDesc: 'Personalizza il risultato',
    generate: 'Genera Sketch',
    generating: 'Generazione...',
    output: 'Output',
    singleView: 'Vista Singola',
    studySheet: 'Tavola Studio',
    view: 'Vista',
    board: 'Tavola',
    style: 'Stile',
    surface: 'Superficie',
    detail: 'Dettaglio',
    finishing: 'Finishing',
    texture: 'Texture',
    cleanDesign: 'Design Pulito',
    cleanDesignDesc: 'Nessuna quota, annotazione o dimensione',
    suggestPalette: 'Suggerisci Palette',
    suggestingPalette: 'Analisi...',
    suggestPaletteHint: 'Analizza i colori dal tuo prodotto',
    result: 'Risultato',
    compare: 'Confronta',
    original: 'Originale',
    sketch: 'Sketch',
    vectorDownload: 'Vector .SVG',
    vectorWarning: '⏳ La generazione del file SVG vettoriale può richiedere 30–90 secondi a seconda della complessità dell\'immagine. Procedere?',
    vectorGenerating: 'Vettorizzando…',
    vectorError: 'Generazione vettore fallita. Riprova.',
    download: 'Download',
    markerBgNote: 'Splash di marker grezzo dietro il prodotto · bordi bold nero + bianco',
    textureComboNote: 'Combo: {t1} + {t2} — l\'AI distribuirà le texture intelligentemente',
    selected: 'selezionati',
    freeLimit: 'Hai usato i tuoi 2 render gratuiti. Abbonati per render illimitati senza watermark.',
    watermarkBanner: 'Render gratuito — con watermark. Abbonati per esportare senza.',
    upgrade: 'Abbonati',
    promoActive: 'Promo attiva',
    promoExpiry: 'Scade 23 apr 2026',
    promoRendersLeft: 'render rimasti',
    promoExhausted: 'Hai esaurito i render promo.',
    promoApplied: '✅ Codice promo applicato! Hai 2 render gratuiti senza watermark.',
    promoInvalid: '❌ Codice promo non valido.',
    promoPrompt: 'Inserisci il codice promo:',
    promoLink: 'Hai un codice promo?',
    correctionsLabel: 'Correggi il Design',
    correctionsPlaceholder: 'Es: rendi il prodotto più rotondo, aggiungi una maniglia sul lato...',
    correctionsApply: 'Applica correzione',
    correctionsNote: 'Pagamento sicuro via Stripe. Il render verrà rigenerato con le tue istruzioni.',
    correctionsLabel: 'Correzioni',
    correctionsPlaceholder: 'Es: rendi i bordi più netti, usa toni più caldi...',
    // Tabs
    tabHome: 'Home',
    tabPlans: 'Piani',
    tabSettings: 'Impostazioni',
    // Pricing page
    pricingTitle: 'Abbonamenti',
    pricingSubtitle: 'Scegli il tuo piano',
    freeTierDesc: '🎨 Piano Gratuito — 2 render al mese con filigrana SketchForge',
    subscriptionActive: 'Abbonamento attivo',
    expiresOn: 'scade il',
    oneTimeOfferBadge: '🎁 OFFERTA UNA TANTUM',
    starterPackTitle: 'Starter Pack — 3 Render',
    starterPackDesc: '3 render senza watermark, acquistabili una sola volta. Perfetto per provare SketchForge.',
    starterPackFeatures: ['3 render HD', 'Nessuna filigrana', 'Tutti gli stili', 'Acquisto unico'],
    alreadyPurchased: 'Già acquistato ✓',
    buyNow: 'Acquista ora',
    mostPopular: 'Più popolare',
    subscribed: 'Abbonato ✓',
    subscribeNow: 'Abbonati ora',
    iframeAlert: 'Il checkout funziona solo dall\'app pubblicata. Apri l\'app in una nuova scheda.',
    alreadyPurchasedAlert: 'Hai già acquistato il Starter Pack!',
    planMonthly: { name: 'Monthly', period: '/ mese', features: ['Render illimitati', 'Tutti gli stili sketch', 'Export HD', 'Colori Pantone'] },
    planSemestral: { name: 'Semestral', period: '/ 6 mesi', savings: 'Risparmia €14,94', features: ['Render illimitati', 'Tutti gli stili sketch', 'Export HD', 'Colori Pantone', 'Priorità di elaborazione'] },
    planYearly: { name: 'Yearly', period: '/ anno', savings: 'Risparmia €79,88', features: ['Render illimitati', 'Tutti gli stili sketch', 'Export HD', 'Colori Pantone', 'Priorità di elaborazione', 'Accesso anticipato alle novità'] },
  },
  en: {
    appSubtitle: 'Industrial Design AI',
    heroTitle: 'From idea to sketch',
    heroTitleAccent: 'professional',
    heroDesc: 'Upload a photo, drawing or rough idea and transform it into an industrial design sketch with Pantone colors.',
    restart: 'Restart',
    settings: 'Settings',
    settingsDesc: 'Customize the result',
    generate: 'Generate Sketch',
    generating: 'Generating...',
    output: 'Output',
    singleView: 'Single View',
    studySheet: 'Study Sheet',
    view: 'View',
    board: 'Layout',
    style: 'Style',
    surface: 'Surface',
    detail: 'Detail',
    finishing: 'Finishing',
    texture: 'Texture',
    cleanDesign: 'Clean Design',
    cleanDesignDesc: 'No quotes, annotations, or dimension labels',
    suggestPalette: 'Suggest Palette',
    suggestingPalette: 'Analyzing...',
    suggestPaletteHint: 'Analyze colors from your product image',
    result: 'Result',
    compare: 'Compare',
    original: 'Original',
    sketch: 'Sketch',
    vectorDownload: 'Vector .SVG',
    vectorWarning: '⏳ Generating an SVG vector file may take 30–90 seconds depending on image complexity. Proceed?',
    vectorGenerating: 'Vectorizing…',
    vectorError: 'Vector generation failed. Please try again.',
    download: 'Download',
    markerBgNote: 'Raw marker color splash behind the object · bold black + white boundary lines',
    textureComboNote: 'Combo: {t1} + {t2} — AI will intelligently blend both textures',
    selected: 'selected',
    freeLimit: 'You have used your 2 free renders. Upgrade to a plan for unlimited renders without watermark.',
    watermarkBanner: 'Free render — watermarked. Upgrade for clean exports.',
    upgrade: 'Upgrade',
    promoActive: 'Promo active',
    promoExpiry: 'Expires Apr 23 2026',
    promoRendersLeft: 'renders left',
    promoExhausted: 'You have used all your promo renders.',
    promoApplied: '✅ Promo code applied! You have 2 free watermark-free renders.',
    promoInvalid: '❌ Invalid promo code.',
    promoPrompt: 'Enter promo code:',
    promoLink: 'Have a promo code?',
    correctionsLabel: 'Correct the Design',
    correctionsPlaceholder: 'E.g. make the product rounder, add a handle on the side...',
    correctionsApply: 'Apply correction',
    correctionsNote: 'Secure payment via Stripe. The render will be regenerated with your instructions.',
    correctionsLabel: 'Corrections',
    correctionsPlaceholder: 'E.g. sharper edges, warmer tones, more detail on handles...',
    // Tabs
    tabHome: 'Home',
    tabPlans: 'Plans',
    tabSettings: 'Settings',
    // Pricing page
    pricingTitle: 'Pricing',
    pricingSubtitle: 'Choose your plan',
    freeTierDesc: '🎨 Free Plan — 2 renders per month with SketchForge watermark',
    subscriptionActive: 'Active subscription',
    expiresOn: 'expires on',
    oneTimeOfferBadge: '🎁 ONE-TIME OFFER',
    starterPackTitle: 'Starter Pack — 3 Renders',
    starterPackDesc: '3 watermark-free renders, purchasable once. Perfect for trying SketchForge.',
    starterPackFeatures: ['3 HD renders', 'No watermark', 'All styles', 'One-time purchase'],
    alreadyPurchased: 'Already purchased ✓',
    buyNow: 'Buy now',
    mostPopular: 'Most popular',
    subscribed: 'Subscribed ✓',
    subscribeNow: 'Subscribe now',
    iframeAlert: 'Checkout only works from the published app. Open the app in a new tab.',
    alreadyPurchasedAlert: 'You have already purchased the Starter Pack!',
    planMonthly: { name: 'Monthly', period: '/ month', features: ['Unlimited renders', 'All sketch styles', 'HD export', 'Pantone colors'] },
    planSemestral: { name: 'Semestral', period: '/ 6 months', savings: 'Save €14.94', features: ['Unlimited renders', 'All sketch styles', 'HD export', 'Pantone colors', 'Priority processing'] },
    planYearly: { name: 'Yearly', period: '/ year', savings: 'Save €79.88', features: ['Unlimited renders', 'All sketch styles', 'HD export', 'Pantone colors', 'Priority processing', 'Early access to new features'] },
  },
};

export function LangProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('sf_lang') || 'it');
  const toggle = () => {
    const next = lang === 'it' ? 'en' : 'it';
    localStorage.setItem('sf_lang', next);
    setLang(next);
  };
  const t = (key) => translations[lang][key] || key;
  return (
    <LangContext.Provider value={{ lang, toggle, t }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang() {
  return useContext(LangContext);
}